---

# This playbook generates OpenVPN configuration for clients (inline and archive)

### USAGE:
# ansible-playbook -i inventories/server -e "HOSTS=all" gen_client_conf.yml -vv
# - if sudo password is needed on server (-K flag tells Ansible to ask for password):
# ansible-playbook -K -i inventories/server -e "HOSTS=all" gen_client_conf.yml -vv

- name: "Setup OpenVPN server"
  hosts: "{{ HOSTS }}"
  gather_facts: no
  become: yes
  roles:
  - generate_client_configuration

...
